### ISSUE TITLE
Bundle configuration succeeds without bundle-configuration directory

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr#142]
The `configuration:dist` command generates a bundle configuration even if no `bundle-configuration` directory has been created for the project. Instead this situation should result into an sbt error.

The current code only throws this sbt error if:
- The generated bundle.conf is empty AND
- The `bundle-configuration` directory exists

https://github.com/typesafehub/sbt-conductr/blob/master/src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala#L427

Not sure why we have the `bundle.conf` check at that place. Tests are showing that the generated bundle.conf is always filled (e.g. with the compatibility version). Therefore I suggest to remove the `bundle.conf` check and only check if `bundle-configuration` the directory exists.

**Comment by huntc** [comment]
You can generate bundle configurations from settings only ie you don't need a directory. Does that help?

**Comment by markusjura** [comment]
The `generatedConf` at https://github.com/typesafehub/sbt-conductr/blob/master/src/main/scala/com/lightbend/conductr/sbt/BundlePlugin.scala#L428 is never empty - even if I haven't specified any bundle configuration settings. Therefore the current logic never fails.

**Comment by huntc** [comment]
@markusjura Is this problem still outstanding?
