### ISSUE TITLE
java.lang.NoClassDefFoundError: Descriptor$CircuitBreakerId

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr#159]
@rodc87 in the [lagom](https://gitter.im/lagom/lagom) gitter channel got the following error when using sbt-conductr 2.1.3 with the latest chirper project:

```
com.google.common.util.concurrent.ExecutionError: 
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/lightbend/lagom/javadsl/api/Descriptor$CircuitBreakerId
```

sbt-conductr 2.1.2 worked for him.

**Comment by huntc** [comment]
He needs to use Lagom rc1
