### ISSUE TITLE
Dependency issue after adding plugin

### ISSUE THREAD

**Issue by cmbaxter** [typesafehub/sbt-conductr#166]
I added the plugin to my my project's `project/plugins.sbt` file and after trying to open up an sbt shell, I get the following error:

```
unresolved dependency: org.glassfish.hk2#hk2-utils;2.19: not found
```

Anyone else ever seen this?  I can't seem to find a way around it.

**Comment by huntc** [comment]
Sorry for the delay - does this issue remain for you?

**Comment by huntc** [comment]
Closing due to a lack of reply
