### ISSUE TITLE
Support Lagom Scala

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr#192]
Lagom Scala is currently not supported by sbt-conductr. No defaults are set when enabling the plugin `LagomScala`. Therefore, the following exception is thrown when loading the sbt console:

```
[info] [error] References to undefined settings:
[info] [error]
[info] [error]   simpleImpl/configuration:bundleNrOfCpus from simpleImpl/configuration:nrOfCpusConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:116)
[info] [error]
[info] [error]   simpleImpl/bundle:bundleDiskSpace from simpleImpl/bundle:diskSpaceConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:107)
[info] [error]
[info] [error]   simpleImpl/configuration:bundleDiskSpace from simpleImpl/configuration:diskSpaceConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:107)
[info] [error]
[info] [error]   simpleImpl/bundle:bundleNrOfCpus from simpleImpl/bundle:nrOfCpusConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:116)
[info] [error]
[info] [error]   simpleImpl/configuration:bundleMemory from simpleImpl/configuration:stage ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:81)
[info] [error]
[info] [error]   simpleImpl/configuration:bundleMemory from simpleImpl/configuration:dist ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:80)
[info] [error]
[info] [error]   simpleImpl/configuration:bundleMemory from simpleImpl/configuration:memoryConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:109)
[info] [error]
[info] [error]   simpleImpl/bundle:bundleMemory from simpleImpl/bundle:memoryConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:109)
[info] [error]
[info] [error] Use 'last' for the full log.
[info] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

We would need to enhance sbt-conductr to introspect the `LagomScala` plugin as well and based on that add the defaults for a Lagom project, as in: https://github.com/typesafehub/sbt-conductr/blob/master/src/main/scala/com/lightbend/conductr/sbt/LagomBundlePlugin.scala#L67-L73

**Comment by huntc** [comment]
Requires a new conductr-lib post the acceptance of https://github.com/typesafehub/conductr-lib/pull/121

**Comment by markusjura** [comment]
@longshorej Can this be closed?

**Comment by huntc** [comment]
Yes, I believe that it can now.

**Comment by dfurmans** [comment]
Hi,
I still have the same error  
bundle:bundleNrOfCpus from onlinediscountservice/bundle:nrOfCpusConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:127)
So update conductr-lib version plugin dose not work

**Comment by markusjura** [comment]
@dfurmans The latest sbt-conductr version 2.3.4 has support for Lagom Scala. sbt-conductr also adds the correct conductr-lib dependency to your project. Here is one project example where you do not get the sbt errors: https://github.com/typesafehub/sbt-conductr/tree/master/sbt-conductr-tester/lagom-scala-bundle

**Comment by dfurmans** [comment]
@markusjura But I would like to skip conductr and build application to RPM package

**Comment by markusjura** [comment]
@dfurmans To not use ConductR, simply remove the `sbt-conductr` plugin from the `plugins.sbt`.

**Comment by dfurmans** [comment]
dose not work. from lagom doc: Running a package requires the provision of a service locator implementation i.e. something that provides the ability for your service to be able to lookup the location of another dynamically at runtime. At a technical level, you provide an implementation of a ServiceLocator.
https://www.lagomframework.com/documentation/1.3.x/scala/ProductionOverview.html#Deploying-to-other-platforms

**Comment by markusjura** [comment]
@dfurmans Yes, it is correct that the tool on wich you deploy your Lagom application needs to implement Lagom's service locator interface. `sbt-conductr` is adding the dependency [lagom1-scala-conductr-bundle-lib](https://github.com/typesafehub/conductr-lib/tree/master/lagom1-scala-conductr-bundle-lib) to the Lagom project that implements Lagom's service locator for ConductR: https://github.com/typesafehub/conductr-lib/blob/master/lagom1-scala-conductr-bundle-lib/src/main/scala/com/typesafe/conductr/bundlelib/lagom/scaladsl/ConductRServiceLocator.scala

So if you want to deploy your application on ConductR, then you need to use `sbt-conductr`. Otherwise, you need to add another dependency to your Lagom project, that implements the service locator interface for your target deployment platform. One option is to perform service location via DNS SRV records in which you could use the following service implementation: https://github.com/typesafehub/service-locator-dns

DNS SRV records are supported on Kubernetes, DC/OS and other platforms.

In general, this is a Lagom related discussion. Please open an issue against https://github.com/lagom/lagom in case you have further input.

**Comment by ignasi35** [comment]
Hi @dfurmans , is this still a concern for you? Do you want to continue the discussion in https://github.com/lagom/lagom as suggested by @markusjura and close this?

You may also be interested checking the [mailing list](https://groups.google.com/forum/#!forum/lagom-framework) or the Gitter [channel](https://gitter.im/lagom/lagom) where other users can share their ideas for deployments strategies.
