### ISSUE TITLE
Set BundleKeys.conductrTargetVersion to ConductrVersion.V2

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr#212]
By default, the `BundleKeys.conductrTargetVersion` is set to `ConductrVersion.V1_1`.

ConductR 2.0.0 is released so we should change the default to `ConductrVersion.V2`.

As a consequence, Lagom bundles will generate the endpoints in the ACL format instead of the services format.

**Comment by huntc** [comment]
Yeah, let's do it!

@longshorej Can you pick this up amongst your sbt-conductr tasks?

**Comment by markusjura** [comment]
Sorry @longshorej. My day begins earlier so I've fixed this one already with PR https://github.com/typesafehub/sbt-conductr/pull/215.
