### ISSUE TITLE
generateInstallationScript uses development configuration

### ISSUE THREAD

**Issue by markusjura** [typesafehub/sbt-conductr#260]
The `generateInstallationScript` is aimed for staging or production usage but in the context of Lagom, it deploys the `conductr-cassandra` bundle with a development configuration. This configuration is removing the data in Cassandra, once the service instance has been stopped. This might not be the indentation of the user, see: https://support.lightbend.com/agent/case/8576

We should document the usage of the `generateInstallationScript` in the context of the Lagom and how to modify it to for staging and production usage.

**Comment by huntc** [comment]
Cassandra config is no longer generated. Closing.
