### ISSUE TITLE
Play conductr libs should support auto-downing

### ISSUE THREAD

**Issue by bayarmunkh** [typesafehub/sbt-conductr#269]
Hi,

When SBR downs a play app/node, it stays hanging, requires manual stopping. So you have to implement a handler for `registerOnMemberRemoved` callback in order to the play app follow SBR's decision. I think the play conductr libs should support this out of box.  Also including a handler for `registerOnMemberUp` would be a good idea too.

Thanks

**Comment by huntc** [comment]
Thanks Chka. Moving it over here: https://github.com/typesafehub/conductr-lib/issues/146 - please follow the issue there. I'll close this issue as sbt-conductr and conductr-lib are different.

**Comment by bayarmunkh** [comment]
ah, right. what was i thinking. thanks!
