### ISSUE TITLE
Support conduct logs --follow option

### ISSUE THREAD

**Issue by TimMoore** [typesafehub/sbt-conductr#278]
The `conduct logs` CLI supports a handy `--follow` (or `-f`) option.

https://github.com/typesafehub/conductr-cli/blob/master/conductr_cli/conduct_main.py#L189-L196

Running `conduct logs` from sbt does not support this option:

https://github.com/typesafehub/sbt-conductr/blob/b3b000d5d31c8163bd75cd5e7819c2aa1aa78ba8/src/main/scala/com/lightbend/conductr/sbt/ConductRPlugin.scala#L684-L685

```
> conduct logs --help
usage: conduct logs [-h] [--scheme SCHEME] [--host HOST] [-i IP] [-p PORT]
                    [--base-path BASE_PATH] [-v] [--disable-instructions] [-q]
                    [--long-ids] [--api-version {1,2}]
                    [--settings-dir CLI_SETTINGS_DIR]
                    [--custom-settings-file CUSTOM_SETTINGS_FILE]
                    [--custom-plugins-dir CUSTOM_PLUGINS_DIR] [-n LINES] [-f]
                    [--utc]
                    bundle

positional arguments:
  bundle                The ID or name of the bundle

optional arguments:
  -h, --help            show this help message and exit
  --scheme SCHEME       The optional ConductR scheme, defaults to http
  --host HOST           The optional ConductR host
                        Defaults to one of the value in this order:
                        1. $CONDUCTR_HOST
                        2. $CONDUCTR_IP
                        3. IP address of the docker VM or
                        4. 127.0.0.1
  -i IP, --ip IP        The optional ConductR IP
                        Defaults to one of the value in this order:
                        1. $CONDUCTR_IP
                        2. IP address of the docker VM
                        3. 127.0.0.1
  -p PORT, --port PORT  The optional ConductR port
                        Defaults to $CONDUCTR_PORT or 9005
  --base-path BASE_PATH
                        The optional ConductR base path
                        Defaults to $DEFAULT_BASE_PATH or /
  -v, --verbose         Print detailed information of the command
  --disable-instructions
                        Disables further instruction output after the command has been succeeded
                        Defaults to False
  -q                    Prints affected bundle id on screen if enabled
                        Defaults to False
  --long-ids            Print long Bundle IDs
  --api-version {1,2}   Sets which ConductR api version to be used
                        Defaults to 2
  --settings-dir CLI_SETTINGS_DIR
                        Directory where ConductR CLI settings are stored
                        Defaults to /Users/tmoore/.conductr
  --custom-settings-file CUSTOM_SETTINGS_FILE
                        Configuration where custom settings for ConductR CLI are stored in HOCON format
                        Defaults to /Users/tmoore/.conductr/settings.conf
  --custom-plugins-dir CUSTOM_PLUGINS_DIR
                        Directory where custom plugins for ConductR CLI are stored
                        Defaults to /Users/tmoore/.conductr/plugins
  -n LINES, --lines LINES
                        The number of logs to fetch
                        Defaults to 10
  -f, --follow          Outputs log events as they occur. Analogous to UNIX's `tail -F`
  --utc                 Convert the date/time of the events to UTC
[success] Total time: 2 s, completed 11/07/2017 11:08:55 PM
> conduct logs -f hello-impl
[error] Usage: conduct logs --help
[error] conduct logs -f hello-impl
[error]                 ^
```

**Comment by fsat** [comment]
We should also support the additional command `deploy`, `backup`, `restore`, and also update the additional switches now exposed through `load` command.

**Comment by fsat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SBT ConductR: Update with latest commands and switches from CLI](https://trello.com/c/B8yzXMVy/858-sbt-conductr-update-with-latest-commands-and-switches-from-cli)

**Comment by longshorej** [comment]
The tricky thing about `-f` is that pressing `CTRL-C`exits SBT. You can set `Keys.cancelable in Global := true` for your project, or we could do it in the plugin itself, but perhaps a user of the plugin doesn't want that setting. There isn't a way to set it per-task, it's a global SBT setting.

Another idea would be to poll for input in `conduct logs` and exit if the user presses a q, and ensure `connectInput` is set for the `conduct` task.

Thoughts?

**Comment by TimMoore** [comment]
@longshorej the continuous file-watch features of sbt, Play and Lagom now all exit on Enter, so that's probably the best pattern to follow.

- [Lagom](https://github.com/lagom/lagom/blob/f7fff9c1630a4f003b33dba6256e27733a6ae4e7/dev/build-tool-support/src/main/scala/com/lightbend/lagom/dev/ConsoleHelper.scala#L29-L32)
- [Play](https://github.com/playframework/playframework/blob/2257a77fe3023fcd53f8488d3e9d007ceada464e/framework/src/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala#L59-L75)
- [sbt](https://github.com/sbt/sbt/blob/34945af6314dee3c9ea55a76c882007f44819509/main-command/src/main/scala/sbt/Watched.scala#L23)
