### ISSUE TITLE
enabling UniversalPlugin on docs project causes references to undefined settings

### ISSUE THREAD

**Issue by dpennell** [typesafehub/sbt-conductr#279]
I have a docs subproject (paradox).  Enabling  and I use `UniversalPlugin` so I can zip up the site causes `sbt-conductr` to fail with the following:

> [error] References to undefined settings: 
> [error] 
> [error]   docs/bundle:bundleMemory from docs/bundle:memoryConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:118)
> [error] 
> [error]   docs/configuration:bundleMemory from docs/configuration:memoryConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:118)
> [error] 
> [error]   docs/bundle:bundleNrOfCpus from docs/bundle:nrOfCpusConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:127)
> [error] 
> [error]   docs/configuration:bundleNrOfCpus from docs/configuration:nrOfCpusConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:127)
> [error] 
> [error]   docs/bundle:bundleDiskSpace from docs/bundle:diskSpaceConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:116)
> [error] 
> [error]   docs/configuration:bundleMemory from docs/configuration:stage ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:88)
> [error] 
> [error]   docs/configuration:bundleMemory from docs/configuration:dist ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:87)
> [error] 
> [error]   docs/configuration:bundleDiskSpace from docs/configuration:diskSpaceConfigName ((com.lightbend.conductr.sbt.BundlePlugin) BundlePlugin.scala:116)

I tried disabling `JavaAppPackaging`, to no avail.  Is there a way to prevent `sbt-conductr` from processing a sub-project?

**Comment by huntc** [comment]
`.disablePlugins` on your sub project?

**Comment by dpennell** [comment]
`disablePlugins(ConductrPlugin)` causes:

> sbt.AutoPluginException: Error determining plugins for project 'docs' in /home/sherpa/git/devops/docs:
Contradiction in selected plugins.  These plugins were both included and excluded: com.lightbend.conductr.sbt.ConductrPlugin

but `disablePlugins(BundlePlugin)` solves the problem.  I note that `BundlePlugin` is triggered by `SbtNativePackager`, so this makes sense.

**Comment by huntc** [comment]
Oh ok. Thanks.
